export const successProductMessage = {
  SUCCESS_CREATE_PRODUCT: 'Success create product',
  SUCCESS_CREATE_PRODUCT_VARIANT: 'Success create product variant',
  SUCCESS_UPDATE_PRODUCT: 'Success update product',
  SUCCESS_UPDATE_PRODUCT_VARIANT: 'Success update product variant',
  SUCCESS_DELETE_PRODUCT: 'Success delete product',
  SUCCESS_DELETE_PRODUCT_VARIANT: 'Success delete product variant',
  SUCCESS_FIND_PRODUCT: 'Success find product',
  SUCCESS_FIND_CATEGORY: 'Success find category',
  SUCCESS_FIND_VARIANT: 'Success find variant',
  SUCCESS_CREATE_VARIANT: 'Success create variant',
  SUCCESS_UPDATE_VARIANT: 'Success update variant',
  SUCCESS_DELETE_VARIANT: 'Success delete variant',
  SUCCESS_CREATE_CATEGORY: 'Success create category',
  SUCCESS_UPDATE_CATEGORY: 'Success update category',
  SUCCESS_DELETE_CATEGORY: 'Success delete category',
  SUCCESS_FIND_ALL_PRODUCT: 'Success find all product',
  SUCCESS_FIND_ALL_CATEGORY: 'Success find all category',
};
