FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm
# RUN pnpm config set store-dir /app/.pnpm-store

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

EXPOSE 8081

CMD ["pnpm", "start:dev"]
