export const errProductMessage = {
  ERROR_CREATE_PRODUCT: 'Error create product',
  ERROR_UPDATE_PRODUCT: 'Error update product',
  ERROR_DELETE_PRODUCT: 'Error delete product',
  ERROR_FIND_PRODUCT: 'Error find product',
  ERROR_FIND_CATEGORY: 'Error find category',
  ERROR_FIND_VARIANT: 'Error find variant',
  ERROR_CREATE_VARIANT: 'Error create variant',
  ERROR_UPDATE_VARIANT: 'Error update variant',
  ERROR_DELETE_VARIANT: 'Error delete variant',
  ERROR_CREATE_CATEGORY: 'Error create category',
  ERROR_UPDATE_CATEGORY: 'Error update category',
  ERROR_DELETE_CATEGORY: 'Error delete category',
  ERROR_FIND_ALL_PRODUCT: 'Error find all product',
  ERROR_FIND_ALL_CATEGORY: 'Error find all category',
  ERROR_CATEGORY_NAME_EXIST: 'Category name already exist',
  ERROR_CATEGORY_NOT_FOUND: 'Category not found',
  ERROR_VARIANT_NOT_FOUND: 'Variant not found',
};
